# Use an official Python image as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy your Flask application code to the container
COPY . .

# Install Oracle Instant Client and Python extension
RUN apt-get update

# Install any other required dependencies
RUN pip install -r requirements.txt

# Expose the port your Flask app will run on
EXPOSE 5000

# Run your Flask application
CMD ["python", "app.py"]
