FROM node:20 as builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the entire Angular project to the container
COPY . .

# Build the Angular application
RUN npm run build --prod

# Create a new image for running the Angular app
FROM nginx:1.19

# Copy the built Angular app from the builder stage to the Nginx directory
COPY --from=builder /app/dist/myapp /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start the Nginx web server
CMD ["nginx", "-g", "daemon off;"]
